import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/ui/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import GetCartContext from "@/components/context/CartContext";
import MySassion from "@/components/mySession/MySassion";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    // 1. أضفنا الخاصية هنا للـ html
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} font-sans antialiased`}
        // 2. وأضفناها هنا للـ body لتجنب إضافات المتصفح مثل ColorZilla
        suppressHydrationWarning={true} 
      >
        <MySassion>
          <GetCartContext>
            <Navbar />

            <div className="container mx-auto">
              <Toaster />
              {children}
            </div>

            <Footer />
          </GetCartContext>
        </MySassion>
      </body>
    </html>
  );
}